databases:
  - name: novaris-agro-postgres
    databaseName: novaris_agro
    user: novaris_agro

services:
  - type: web
    name: novaris-agro-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: novaris-agro-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_MINUTES
        value: "720"
      - key: SEED_DEMO
        value: "true"
      - key: ALLOWED_ORIGINS
        value: https://novaris-agro-web.onrender.com
      - key: FRONTEND_URL
        value: https://novaris-agro-web.onrender.com
      - key: APP_VERSION
        value: "1.0.0"
